on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            binary-name: bing-webserver.exe
          - target: x86_64-unknown-linux-musl
            binary-name: bing-webserver
          - target: i686-unknown-linux-musl
            binary-name: release/bing-webserver
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: -r --target ${{ matrix.target }}
      - name: Debug Directory structure
        run: |
          sudo apt install -y tree
          tree
      - name: Zip Binary
        run: zip bing-webserver-${{ matrix.target }}.zip target/${{ matrix.target }}/release/${{ matrix.binary-name }}
      - uses: actions/cache@v3
        with:
          path: |
            bing-webserver-${{ matrix.target }}.zip
          key: bing-webserver-${{ matrix.target }}
  release:
    name: release to github 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            *.zip
          key: bing-webserver-${{ github.ref_name }}
          restore-keys: |
            bing-webserver-
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/release/*.zip
