on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: -r --target ${{ matrix.target }}
      - name: Zip Binary
        run: (cd target/release && zip bing-webserver-${{ matrix.target }}.zip bing-webserver)
      - uses: actions/cache@v3
        with:
          path: |
            target/release/bing-webserver-${{ matrix.target }}.zip
          key: bing-webserver-${{ matrix.target }}
  release:
    name: release to github 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            target/release/
          key: bing-webserver-${{ github.ref_name }}
          restore-keys: |
            bing-webserver-
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/release/*.zip
